### ISSUE TITLE
Clean the training data

### ISSUE THREAD

**Issue by varvara-l** [RealAntonVoronov/computational_humour#2]
Clean the subtitles corpus:

1. remove examples where source is not English and/or target is not Portuguese
2. remove examples with a large (e.g. >= 2) difference in length
3. remove examples where source or target contains multiple sentences

check out some corpus cleaning tools:
https://github.com/M4t1ss/parallel-corpora-tools - can probably replace everything written above & more (there's a script which performs BPE)
https://github.com/bitextor/bicleaner - corpus filtering

**Comment by RealAntonVoronov** [comment]
resolved in preprocess_data
